name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.annoyingapi.AnnoyingPlugin
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI
