name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.annoyingexample.ExamplePlugin
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - ViaVersion

# You can either specify options here or in the plugin's main class (recommended)
annoying:
  pluginOptions:
    dependencies:
      ViaVersion:
        platforms:
          HANGAR:
            author: ViaVersion
            identifier: ViaVersion
          SPIGOT: 19254
        required: true
        enableAfterDownload: true
  bStatsOptions:
    id: 12345
    fileName: "stats.yml"
    fileOptions:
      createDefaultFile: false
    toggleKey: "enable-stats"
  messagesOptions:
    fileName: "msgs.yml"
    keys:
      globalPlaceholders: "placeholders"
      splitterJson: "splitter.json"
      splitterPlaceholder: "splitter.placeholder"
      noPermission: "no-permission"
      playerOnly: "player-only"
      invalidArguments: "invalid-arguments"
      disabledCommand: "disabled-command"

commands:
  test:
    description: Test command
    aliases:
      - t

permissions:
  test.command:
    description: Permission to use test command
    default: true
