name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.annoyingexample.ExamplePlugin
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - ViaVersion

commands:
  test:
    description: Test command
    aliases:
      - t

permissions:
  test.command:
    description: Permission to use test command
    default: true
