name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.annoyingexample.ExamplePlugin
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - ViaVersion

annoying:
  bStatsId: 12345
  bStatsFileName: "stats.yml"
  bStatsOptions:
    createDefaultFile: false
  messagesFileName: "msgs.yml"
  messageKeys:
    globalPlaceholders: "placeholders"
    splitterJson: "splitter.json"
    splitterPlaceholder: "splitter.placeholder"
    noPermission: "no-permission"
    playerOnly: "player-only"
    invalidArguments: "invalid-arguments"
    disabledCommand: "disabled-command"
  dependencies:
    ViaVersion:
      platforms:
        HANGAR:
          author: ViaVersion
          identifier: ViaVersion
        SPIGOT: 19254
      required: true
      enableAfterDownload: true

commands:
  test:
    description: Test command
    aliases:
      - t

permissions:
  test.command:
    description: Permission to use test command
    default: true
