name: Maven Publish (Snapshots)
on:
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/maven_publish.yml@main
    with:
      name: Annoying API
      channel: snapshots
    secrets: inherit
