# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build
on:
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'api/**'
      - 'example-plugin/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[no-build]')"
    steps:
      - uses: "actions/checkout@v3.5.3"
      - uses: "gradle/wrapper-validation-action@v1.0.6"
      - name: Set up JDK
        uses: "actions/setup-java@v3.11.0"
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: "actions/upload-artifact@v3.1.2"
        with:
          name: Annoying API
          path: |
            api/build/libs/*.jar
            example-plugin/build/libs/*.jar
