name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3.5.3"
      - uses: "gradle/wrapper-validation-action@v1.0.6"
      - name: Set up JDK
        uses: "actions/setup-java@v3.11.0"
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar with Gradle
        run: ./gradlew build
      - name: Publish artifacts
        uses: "Kir-Antipov/mc-publish@v3.3"
        with:
          modrinth-id: gzktm9GG
          curseforge-id: 728930
          game-versions: |
            >=1.8.8
          game-version-filter: releases
          
          loaders: |
            purpur
            paper
            spigot
          files: |
            api/build/libs/AnnoyingAPI-*[!a-z].jar
            api/build/libs/AnnoyingAPI-*-@(javadoc|sources).jar
            example-plugin/build/libs/*.jar
          changelog: ${{ github.event.release.html_url }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
