name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3.5.3"
      - uses: "gradle/wrapper-validation-action@v1.0.6"
      - name: Set up JDK
        uses: "actions/setup-java@v3.11.0"
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar with Gradle
        run: ./gradlew build
      - name: Publish artifacts
        uses: "Kir-Antipov/mc-publish@v3.3"
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: gzktm9GG
          
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          #curseforge-id: 728930
          
          game-versions: |
            >=1.8.8
          
          changelog: github.event.release.url
          
          files: |
            "api/build/libs/AnnoyingAPI-*.jar"
            "example-plugin/build/libs/AnnoyingExample-*.jar"
