name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: gzktm9GG
      curseforge: 728930
      files: |
        api/build/libs/AnnoyingAPI-*[!a-z].jar
        api/build/libs/AnnoyingAPI-*-@(javadoc|sources).jar
        example-plugin/build/libs/*.jar
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
