name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      java: 11
      modrinth: gzktm9GG
      curseforge: 728930
      files: |
        build/libs/AnnoyingAPI-*[!a-z].jar
        build/libs/AnnoyingAPI-*-@(javadoc|sources).jar
    secrets: inherit
    permissions:
      contents: write
