name: Maven Publish (Releases)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/maven_publish.yml@main
    with:
      name: Annoying API
      channel: releases
    secrets: inherit
